# INTRODUCTION

Based on the variables:
Temperature (AT), Pressure (V), Humidity (AP) and Vacuum (RH) compiled in a dataset we have been tasked by a Combined Cycle Power Plant to predict their Energy Output (PE) with a very strong predictive accuracy.

**Problem Statement** : This is a Regression Problem which we will be solving using Artificial Neural Networks for Regression

# Artificial Neural Network

### Importing the libraries

In [1]:
 import numpy as np
 import pandas as pd
 import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Part 1 - Data Preprocessing

### Importing the dataset

In [6]:
dataset = pd.read_excel("/content/drive/MyDrive/Folds5x2_pp.xlsx")
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [7]:
# Creating matrix features and dependent variable vector

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [9]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
# We will use rectifier activation with 6 units of neurons

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [13]:
# We will use rectifier activation with 6 units of neurons

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [23]:
# Activation function to be used for Regression is None as default

ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
# We will use Stochastic Gradient Descent for updating of the weights - so "adam" optimizer
# We will use Loss function of MSE as it is a Regression problem

ann.compile(optimizer="adam", loss="mean_squared_error")

### Training the ANN model on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 16628.6250
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 368.2052
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 357.9824
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 344.1293
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 328.3791
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 310.9158
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 291.3057
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 270.8433
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 248.8051
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 226.2222
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 202.8611
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - lo

### Predicting the results of the Test set

In [19]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[433.43 431.23]
 [464.59 460.01]
 [468.12 461.14]
 ...
 [475.34 473.26]
 [442.05 438.  ]
 [461.3  463.28]]


In [22]:
# Calculate R-squared
from sklearn.metrics import r2_score
r_squared = round(r2_score(y_test, y_pred),3)
print("R-squared:", r_squared)

R-squared: 0.899


# CONCLUSION

We have created a predictive model for Energy Output with 89% R2 Scores, which is the best fitting model based on this dataset.

# Streamlit App

We will be creating an app on Streamlit that will help the client to predict their Energy Output values in real-time using this model as a backend

In [24]:
# Saving the model

ann.save("ann_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [25]:
from google.colab import files

files.download("ann_model.h5")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>